ALTER TABLE "sale_items" ADD COLUMN IF NOT EXISTS "taxAmount" DOUBLE PRECISION;
ALTER TABLE "sale_record_items" ADD COLUMN IF NOT EXISTS "taxAmount" DOUBLE PRECISION;
ALTER TABLE "sale_returns" ADD COLUMN IF NOT EXISTS "taxAmount" DOUBLE PRECISION;
ALTER TABLE "sale_return_items" ADD COLUMN IF NOT EXISTS "taxAmount" DOUBLE PRECISION;
ALTER TABLE "credit_notes" ADD COLUMN IF NOT EXISTS "taxAmount" DOUBLE PRECISION;
