[build]
  # Base directory (root of the repository)
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "public"
  
  # No build command needed since files are already built
  command = ""

# Specific build environment
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"

# Redirects configuration for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
