[build]
  # Directory to change to before starting a build
  base = "./public"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "./public"
  
  # Default build command
  command = "npm run build"

# Specific build environment
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NPM_FLAGS = "--legacy-peer-deps"

# Redirects configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (these should be set in Netlify dashboard)
# [build.environment]
#   NODE_ENV = "production"
#   NEXT_PUBLIC_API_URL = "your-api-url-here"
#   NEXTAUTH_URL = "your-netlify-app-url"
#   NEXTAUTH_SECRET = "your-secret-key"

# For Single Page Applications (SPA) - handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://your-api-url.com;"

# Environment variables context (uncomment and set as needed)
# [context.production.environment]
#   NODE_ENV = "production"
#   NEXT_PUBLIC_API_URL = "https://your-production-api.com"

# [context.deploy-preview.environment]
#   NODE_ENV = "staging"
#   NEXT_PUBLIC_API_URL = "https://staging-api.yourdomain.com"

# [context.branch-deploy.environment]
#   NODE_ENV = "development"
#   NEXT_PUBLIC_API_URL = "https://dev-api.yourdomain.com"
