[build]
  # Base directory (root of the repository)
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "public/dist"
  
  # Build command - only build the client
  command = "cd public && npm install && npm run build"

# Specific build environment
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirects configuration for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (set these in Netlify dashboard)
[build.environment]
  NODE_ENV = "production"
  # NEXT_PUBLIC_API_URL = "your-api-url-here"
  # NEXTAUTH_URL = "your-netlify-app-url"
  # NEXTAUTH_SECRET = "your-secret-key"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
