[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
rootDirectory = "backend"

[deploy]

healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
