[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "npx prisma db push --accept-data-loss --skip-generate && node src/app.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
internal_port = 3000
external_port = 3000

[services.healthcheck]
path = "/"
interval = "30s"
timeout = "10s"
