ALTER TABLE "user_permissions"
ADD COLUMN IF NOT EXISTS "canViewServiceAppointment" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canCreateServiceAppointment" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canEditServiceAppointment" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canDeleteServiceAppointment" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canUpdateServiceAppointmentStatus" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canAssignServiceAppointment" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canViewServiceAppointmentReport" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canViewServiceWorkOrder" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canCreateServiceWorkOrder" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canEditServiceWorkOrder" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canDeleteServiceWorkOrder" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canUpdateServiceWorkOrderStatus" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canAssignServiceWorkOrder" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canViewServiceWorkOrderReport" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canViewServiceContract" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canCreateServiceContract" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canEditServiceContract" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canDeleteServiceContract" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canUpdateServiceContractStatus" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canViewServiceContractReport" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canViewServiceTechnician" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canCreateServiceTechnician" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canEditServiceTechnician" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canDeleteServiceTechnician" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canViewServiceTechnicianReport" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canViewServiceJobCard" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canCreateServiceJobCard" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canEditServiceJobCard" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canDeleteServiceJobCard" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canUpdateServiceJobCardStatus" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canAssignServiceJobCard" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canCheckServiceJobCardQuality" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canViewServiceJobCardReport" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canViewServiceFeedback" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canCreateServiceFeedback" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canRespondServiceFeedback" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canModerateServiceFeedback" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canDeleteServiceFeedback" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canGenerateServiceFeedbackQR" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canViewServiceFeedbackReport" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canViewServiceCarWash" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canCreateServiceCarWash" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canEditServiceCarWash" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canDeleteServiceCarWash" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canViewServiceGarage" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canCreateServiceGarage" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canEditServiceGarage" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canDeleteServiceGarage" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canUpdateServiceGarageStatus" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "servicePermissionsMigrated" BOOLEAN NOT NULL DEFAULT false;

UPDATE "user_permissions" SET
"canViewServiceAppointment" = "canViewServiceAppointment" OR "canViewServiceBusiness",
"canCreateServiceAppointment" = "canCreateServiceAppointment" OR "canCreateServiceBusiness",
"canEditServiceAppointment" = "canEditServiceAppointment" OR "canEditServiceBusiness",
"canDeleteServiceAppointment" = "canDeleteServiceAppointment" OR "canDeleteServiceBusiness",
"canUpdateServiceAppointmentStatus" = "canUpdateServiceAppointmentStatus" OR "canEditServiceBusiness",
"canAssignServiceAppointment" = "canAssignServiceAppointment" OR "canEditServiceBusiness",
"canViewServiceAppointmentReport" = "canViewServiceAppointmentReport" OR "canViewServiceBusinessReport",
"canViewServiceWorkOrder" = "canViewServiceWorkOrder" OR "canViewServiceBusiness",
"canCreateServiceWorkOrder" = "canCreateServiceWorkOrder" OR "canCreateServiceBusiness",
"canEditServiceWorkOrder" = "canEditServiceWorkOrder" OR "canEditServiceBusiness",
"canDeleteServiceWorkOrder" = "canDeleteServiceWorkOrder" OR "canDeleteServiceBusiness",
"canUpdateServiceWorkOrderStatus" = "canUpdateServiceWorkOrderStatus" OR "canEditServiceBusiness",
"canAssignServiceWorkOrder" = "canAssignServiceWorkOrder" OR "canEditServiceBusiness",
"canViewServiceWorkOrderReport" = "canViewServiceWorkOrderReport" OR "canViewServiceBusinessReport",
"canViewServiceContract" = "canViewServiceContract" OR "canViewServiceBusiness",
"canCreateServiceContract" = "canCreateServiceContract" OR "canCreateServiceBusiness",
"canEditServiceContract" = "canEditServiceContract" OR "canEditServiceBusiness",
"canDeleteServiceContract" = "canDeleteServiceContract" OR "canDeleteServiceBusiness",
"canUpdateServiceContractStatus" = "canUpdateServiceContractStatus" OR "canEditServiceBusiness",
"canViewServiceContractReport" = "canViewServiceContractReport" OR "canViewServiceBusinessReport",
"canViewServiceTechnician" = "canViewServiceTechnician" OR "canViewServiceBusiness",
"canCreateServiceTechnician" = "canCreateServiceTechnician" OR "canCreateServiceBusiness",
"canEditServiceTechnician" = "canEditServiceTechnician" OR "canEditServiceBusiness",
"canDeleteServiceTechnician" = "canDeleteServiceTechnician" OR "canDeleteServiceBusiness",
"canViewServiceTechnicianReport" = "canViewServiceTechnicianReport" OR "canViewServiceBusinessReport",
"canViewServiceJobCard" = "canViewServiceJobCard" OR "canViewServiceBusiness",
"canCreateServiceJobCard" = "canCreateServiceJobCard" OR "canCreateServiceBusiness",
"canEditServiceJobCard" = "canEditServiceJobCard" OR "canEditServiceBusiness",
"canDeleteServiceJobCard" = "canDeleteServiceJobCard" OR "canDeleteServiceBusiness",
"canUpdateServiceJobCardStatus" = "canUpdateServiceJobCardStatus" OR "canEditServiceBusiness",
"canAssignServiceJobCard" = "canAssignServiceJobCard" OR "canEditServiceBusiness",
"canCheckServiceJobCardQuality" = "canCheckServiceJobCardQuality" OR "canEditServiceBusiness",
"canViewServiceJobCardReport" = "canViewServiceJobCardReport" OR "canViewServiceBusinessReport",
"canViewServiceFeedback" = "canViewServiceFeedback" OR "canViewServiceBusiness",
"canCreateServiceFeedback" = "canCreateServiceFeedback" OR "canCreateServiceBusiness",
"canRespondServiceFeedback" = "canRespondServiceFeedback" OR "canEditServiceBusiness",
"canModerateServiceFeedback" = "canModerateServiceFeedback" OR "canEditServiceBusiness",
"canDeleteServiceFeedback" = "canDeleteServiceFeedback" OR "canDeleteServiceBusiness",
"canGenerateServiceFeedbackQR" = "canGenerateServiceFeedbackQR" OR "canCreateServiceBusiness",
"canViewServiceFeedbackReport" = "canViewServiceFeedbackReport" OR "canViewServiceBusinessReport",
"canViewServiceCarWash" = "canViewServiceCarWash" OR "canViewServiceBusiness",
"canCreateServiceCarWash" = "canCreateServiceCarWash" OR "canCreateServiceBusiness",
"canEditServiceCarWash" = "canEditServiceCarWash" OR "canEditServiceBusiness",
"canDeleteServiceCarWash" = "canDeleteServiceCarWash" OR "canDeleteServiceBusiness",
"canViewServiceGarage" = "canViewServiceGarage" OR "canViewServiceBusiness",
"canCreateServiceGarage" = "canCreateServiceGarage" OR "canCreateServiceBusiness",
"canEditServiceGarage" = "canEditServiceGarage" OR "canEditServiceBusiness",
"canDeleteServiceGarage" = "canDeleteServiceGarage" OR "canDeleteServiceBusiness",
"canUpdateServiceGarageStatus" = "canUpdateServiceGarageStatus" OR "canEditServiceBusiness",
"canViewServiceBusiness" = false,
"canCreateServiceBusiness" = false,
"canEditServiceBusiness" = false,
"canDeleteServiceBusiness" = false,
"canViewServiceBusinessReport" = false,
"servicePermissionsMigrated" = true
WHERE "servicePermissionsMigrated" = false;
ALTER TABLE "user_permissions" ALTER COLUMN "servicePermissionsMigrated" SET DEFAULT true;


ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "serviceKind" TEXT NOT NULL DEFAULT 'work_order';
UPDATE "work_orders" SET "serviceKind" = 'car_wash' WHERE "serviceKind" = 'work_order' AND "orderNo" LIKE 'CW-%';
UPDATE "work_orders" SET "serviceKind" = 'garage' WHERE "serviceKind" = 'work_order' AND "orderNo" LIKE 'GR-%';
