// Only truly universal categories that apply to every business type
const COMMON_PRODUCT_CATEGORIES = [
  { name: 'Other', slug: 'other' },
];

const BUSINESS_TYPE_CATEGORY_MAP = {
  retail: [
    'General Merchandise',
    'Household Items',
    'Household Plastics',
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Spices & Condiments',
    'Cereals & Grains',
    'Canned Goods',
    'Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Tea & Coffee',
    'Alcoholic Beverages',
    'Tobacco Products',
    'Dairy Products',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Ice Cream',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Frozen Foods',
    'Health & Wellness',
    'Personal Care',
    'Hair Care',
    'Perfumes & Deodorants',
    'Soaps & Body Wash',
    'Laundry & Fabric Care',
    'Detergents',
    'Baby Products',
    'Diapers & Wipes',
    'Cleaning Supplies',
    'Pest Control',
    'Air Fresheners',
    'Oral Care',
    'Feminine Care',
    'Sanitary Pads',
    'Paper Products',
    'Disposable Products',
    'Stationery & Office Supplies',
    'School Supplies',
    'Footwear & Clothing',
    'Toys & Gifts',
    'Batteries & Electrical',
    'Hardware & Security',
    'Shoe Care',
    'Kitchenware',
    'Glassware',
    'Candles & Religious Items',
    'Pet Supplies',
    'Phone Accessories',
    'First Aid',
  ],
  supermarket: [
    'General Merchandise',
    'Household Items',
    'Household Plastics',
    'Wholesale Goods',
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Spices & Condiments',
    'Cereals & Grains',
    'Canned Goods',
    'Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Tea & Coffee',
    'Alcoholic Beverages',
    'Tobacco Products',
    'Dairy Products',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Ice Cream',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Frozen Foods',
    'Personal Care',
    'Hair Care',
    'Soaps & Body Wash',
    'Laundry & Fabric Care',
    'Detergents',
    'Baby Products',
    'Diapers & Wipes',
    'Cleaning Supplies',
    'Pest Control',
    'Air Fresheners',
    'Oral Care',
    'Feminine Care',
    'Sanitary Pads',
    'Paper Products',
    'Disposable Products',
    'Stationery & Office Supplies',
    'School Supplies',
    'Footwear & Clothing',
    'Batteries & Electrical',
    'Kitchenware',
    'Glassware',
    'Pet Supplies',
    'First Aid',
  ],
  wholesale: [
    'General Merchandise',
    'Household Items',
    'Household Plastics',
    'Wholesale Goods',
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Spices & Condiments',
    'Cereals & Grains',
    'Canned Goods',
    'Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Tea & Coffee',
    'Dairy Products',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Fruits',
    'Vegetables',
    'Frozen Foods',
    'Personal Care',
    'Soaps & Body Wash',
    'Laundry & Fabric Care',
    'Detergents',
    'Baby Products',
    'Diapers & Wipes',
    'Feminine Care',
    'Sanitary Pads',
    'Cleaning Supplies',
    'Paper Products',
    'Disposable Products',
    'Stationery & Office Supplies',
    'School Supplies',
    'Hardware & Security',
    'Batteries & Electrical',
    'Kitchenware',
    'Glassware',
  ],
  pharmacy: [
    'Health & Wellness',
    'Personal Care',
    'Hair Care',
    'Perfumes & Deodorants',
    'Soaps & Body Wash',
    'Oral Care',
    'Feminine Care',
    'Sanitary Pads',
    'Baby Products',
    'Diapers & Wipes',
    'Medical Supplies',
    'Pharmaceuticals',
    'Beauty Products',
    'Cosmetics',
    'First Aid',
    'Vitamins & Supplements',
    'Skin Care',
    'Medical Devices',
  ],
  hardware: [
    'Electrical Supplies',
    'Electric Cables & Wires',
    'Switches & Sockets',
    'Circuit Breakers',
    'Lighting & Bulbs',
    'Hardware Tools',
    'Nails & Screws',
    'Plumbing Accessories',
    'Building Hardware',
    'Hardware & Security',
    'Batteries & Electrical',
    'Building Materials',
    'Paints',
    'Plumbing',
    'Electrical',
    'Hardware',
    'Welding Supplies',
    'Adhesives & Sealants',
    'Safety Equipment',
    'Garden Tools',
  ],
  restaurant: [
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Spices & Condiments',
    'Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Dairy Products',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Kitchenware',
    'Glassware',
    'Disposable Products',
    'Paper Products',
    'Cleaning Supplies',
    'Pest Control',
  ],
  bar: [
    'Beverages',
    'Alcoholic Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Food & Grocery',
    'Cooking Oil',
    'Snacks',
    'Confectionery',
    'Glassware',
    'Disposable Products',
    'Paper Products',
    'Cleaning Supplies',
  ],
  restaurant_bar: [
    'Beverages',
    'Alcoholic Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Spices & Condiments',
    'Dairy Products',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Kitchenware',
    'Glassware',
    'Disposable Products',
    'Paper Products',
    'Cleaning Supplies',
  ],
  cafe: [
    'Beverages',
    'Tea & Coffee',
    'Soft Drinks',
    'Bottled Water',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Food & Grocery',
    'Dairy Products',
    'Kitchenware',
    'Glassware',
    'Disposable Products',
    'Paper Products',
  ],
  coffee_shop: [
    'Beverages',
    'Tea & Coffee',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Food & Grocery',
    'Dairy Products',
    'Kitchenware',
    'Glassware',
    'Disposable Products',
    'Paper Products',
  ],
  fast_food: [
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Spices & Condiments',
    'Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Snacks',
    'Confectionery',
    'Disposable Products',
    'Paper Products',
    'Cleaning Supplies',
  ],
  hotel_restaurant: [
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Spices & Condiments',
    'Beverages',
    'Alcoholic Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Tea & Coffee',
    'Dairy Products',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Kitchenware',
    'Glassware',
    'Disposable Products',
    'Paper Products',
    'Cleaning Supplies',
    'Pest Control',
  ],
  bakery: [
    'Bakery',
    'Beverages',
    'Tea & Coffee',
    'Soft Drinks',
    'Bottled Water',
    'Dairy Products',
    'Snacks',
    'Confectionery',
    'Food & Grocery',
    'Cooking Oil',
    'Spices & Condiments',
    'Fruits',
    'Kitchenware',
    'Glassware',
    'Paper Products',
    'Disposable Products',
    'Packaging Materials',
  ],
  service: [
    'General Merchandise',
    'Household Items',
    'Cleaning Supplies',
    'Office Supplies',
    'Stationery & Office Supplies',
  ],
  salon_spa: [
    'Personal Care',
    'Hair Care',
    'Perfumes & Deodorants',
    'Soaps & Body Wash',
    'Health & Wellness',
    'Beauty Products',
    'Cosmetics',
    'Skin Care',
    'Nail Care',
    'Salon Equipment',
    'Disposable Products',
    'Paper Products',
    'Cleaning Supplies',
  ],
  repair_shop: [
    'Hardware Tools',
    'Nails & Screws',
    'Plumbing Accessories',
    'Building Hardware',
    'Hardware & Security',
    'Batteries & Electrical',
    'Electrical Supplies',
    'Spare Parts',
    'Mobile Accessories',
    'Phone Chargers',
    'Screen Protectors',
    'Phone Cases',
    'Laptop Accessories',
    'Repair Tools',
  ],
  manufacturing: [
    'Industrial Supplies',
    'Spare Parts',
    'Hardware Tools',
    'Building Materials',
    'Plumbing Accessories',
    'Electrical Supplies',
    'Hardware & Security',
    'Batteries & Electrical',
    'Raw Materials',
    'Packaging Materials',
    'Safety Equipment',
    'Welding Supplies',
    'Adhesives & Sealants',
  ],
  other: [
    'General Merchandise',
    'Household Items',
    'Food & Grocery',
    'Beverages',
    'Personal Care',
    'Cleaning Supplies',
    'Stationery & Office Supplies',
  ],
};

const slugify = (value = '') => String(value)
  .trim()
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/(^-|-$)/g, '');

const normalizeBusinessType = (businessType = 'other') => {
  const value = String(businessType || 'other').trim().toLowerCase();
  if (BUSINESS_TYPE_CATEGORY_MAP[value]) return value;
  const aliases = {
    retail_store: 'retail',
    shop: 'retail',
    supermarket: 'supermarket',
    wholesale_shop: 'wholesale',
    pharmacy_store: 'pharmacy',
    hardware_store: 'hardware',
    restaurant_bar: 'restaurant_bar',
    cafe_shop: 'cafe',
    coffee: 'coffee_shop',
    fastfood: 'fast_food',
    salon: 'salon_spa',
    spa: 'salon_spa',
    repair: 'repair_shop',
    manufacturing_company: 'manufacturing',
    service_business: 'service',
  };
  return aliases[value] || 'other';
};

const buildCategoryDefinitions = (businessType = 'other') => {
  const normalizedType = normalizeBusinessType(businessType);
  const typeSpecificCategories = BUSINESS_TYPE_CATEGORY_MAP[normalizedType] || BUSINESS_TYPE_CATEGORY_MAP.other;
  const merged = [];
  const seen = new Set();
  const addCategory = (name) => {
    const slug = slugify(name);
    if (!seen.has(slug)) {
      seen.add(slug);
      merged.push({ name, slug, categoryType: 'product' });
    }
  };

  COMMON_PRODUCT_CATEGORIES.forEach((category) => addCategory(category.name));
  typeSpecificCategories.forEach((name) => addCategory(name));

  return merged;
};

export function getDefaultCategoryDefinitionsForBusinessType(businessType = 'other') {
  return buildCategoryDefinitions(businessType);
}

export function getDefaultCategorySlugsForBusinessType(businessType = 'other') {
  return new Set(getDefaultCategoryDefinitionsForBusinessType(businessType).map((category) => category.slug));
}

export function getAllDefaultCategoryDefinitions() {
  const all = [];
  const seen = new Set();
  for (const businessType of Object.keys(BUSINESS_TYPE_CATEGORY_MAP)) {
    for (const category of buildCategoryDefinitions(businessType)) {
      if (!seen.has(category.slug)) {
        seen.add(category.slug);
        all.push(category);
      }
    }
  }
  return all;
}

export function getAllDefaultCategorySlugs() {
  return new Set(getAllDefaultCategoryDefinitions().map((category) => category.slug));
}
