// Broad defaults remain extensible through tenant-owned custom categories.
export const SERVICE_CATEGORY_GROUPS = {
  business: [
    'General Services', 'Consultation', 'Business Consulting', 'Strategy Planning',
    'Financial Advisory', 'Accounting & Bookkeeping', 'Audit Services', 'Tax Consulting',
    'Legal Services', 'HR Consulting', 'Recruitment & Staffing', 'Payroll Services',
    'Marketing Consulting', 'Market Research', 'Feasibility Studies', 'Business Registration',
    'License & Permits', 'Compliance Advisory', 'Risk Assessment', 'Project Management',
    'Change Management', 'Process Optimization', 'Digital Transformation', 'IT Consulting',
    'Administrative Support', 'Virtual Assistance', 'Translation & Interpretation',
    'Secretarial Services', 'Call Centre Services', 'Procurement Services', 'Valuation Services',
    'Insurance Brokerage', 'Investment Advisory', 'Debt Collection', 'Notarial Services',
  ],
  technology: [
    'Software Development', 'Web Development', 'Mobile App Development', 'UI/UX Design',
    'Cloud Services', 'Server Maintenance', 'Network Installation', 'Cybersecurity',
    'Data Recovery', 'IT Support', 'Hardware Repair', 'Computer Repair', 'Laptop Repair',
    'Phone Repair', 'Printer Repair', 'CCTV Installation', 'Access Control Systems',
    'Internet Setup', 'WiFi Installation', 'Data Backup', 'System Integration',
    'Database Management', 'DevOps Services', 'QA Testing', 'Data Analytics',
    'AI & Automation Services', 'Software Implementation', 'Software Maintenance',
    'Web Hosting', 'Domain Registration', 'Telecommunications Services',
  ],
  creative: [
    'Graphic Design', 'Branding & Identity', 'Advertising Services', 'Digital Marketing',
    'Social Media Management', 'Search Engine Optimization', 'Content Writing',
    'Copywriting', 'Public Relations', 'Printing Services', 'Print Services',
    'Signwriting & Sign Installation', 'Publishing Services', 'Animation',
    'Music Production', 'Audio Recording', 'Voice-over Services', 'Video Production',
    'Video Editing', 'Photo Editing', 'Album Design', 'Framing Services',
    'Wedding Photography', 'Event Photography', 'Portrait Photography',
    'Product Photography', 'Corporate Photography', 'Drone Photography',
    'Videography', 'Videography Services', 'Live Streaming',
  ],
  personal: [
    'Haircuts & Styling', 'Beard Trimming & Shaping', 'Razor Shaves', 'Hair Coloring',
    'Scalp Treatment', 'Hair Wash & Conditioning', 'Kids Haircuts', 'Hot Towel Service',
    'Facial Grooming', 'Ear Piercing', 'Facial Treatments', 'Body Treatments',
    'Manicure & Pedicure', 'Nail Extensions', 'Waxing & Hair Removal',
    'Makeup Services', 'Massage Therapy', 'Spa Treatments', 'Tattoo Services',
    'Bridal Makeup', 'Groom Grooming', 'Bridal Hairstyling', 'Groom Hairstyling',
    'Bridal Mehndi/Henna', 'Pre-Wedding Skincare', 'Bridal Trial Sessions',
    'Pre-Wedding Spa', 'Post-Wedding Spa', 'Personal Styling',
    'Tailoring & Alterations', 'Shoe Repair', 'Laundry Services', 'Dry Cleaning',
  ],
  property: [
    'Residential Cleaning', 'Commercial Cleaning', 'Deep Cleaning', 'Carpet Cleaning',
    'Window Cleaning', 'Post-Construction Cleaning', 'Move-in/Move-out Cleaning',
    'Upholstery Cleaning', 'Floor Polishing', 'Pressure Washing', 'Garden Maintenance',
    'Pest Control', 'Waste Management', 'Sanitization Services', 'Disinfection Services',
    'Plumbing Services', 'Electrical Installation & Repair', 'Carpentry & Joinery',
    'Painting & Decorating', 'Roofing Services', 'Masonry & Bricklaying',
    'Tiling & Flooring', 'Welding & Fabrication', 'Glazing Services',
    'Air Conditioning & Refrigeration', 'Appliance Repair', 'Furniture Repair',
    'Solar Installation & Maintenance', 'Generator Maintenance', 'Locksmith Services',
    'Borehole Drilling', 'Water Treatment Services', 'Septic Tank Services',
    'Construction Services', 'Civil Engineering', 'Architectural Services',
    'Quantity Surveying', 'Land Surveying', 'Interior Design', 'Landscaping',
    'Property Management', 'Real Estate Agency', 'Property Inspection',
    'Facilities Management', 'Security Services', 'Fire Safety Services',
  ],
  transport: [
    'Passenger Transport', 'Taxi & Ride Services', 'Bus & Coach Services',
    'Airport Transfers', 'Freight Transport', 'Courier & Delivery', 'Moving Services',
    'Warehousing', 'Distribution Services', 'Customs Clearing', 'Freight Forwarding',
    'Transport & Logistics', 'Transportation', 'Vehicle Repair & Maintenance',
    'Vehicle Diagnostics', 'Tyre Fitting & Wheel Alignment', 'Vehicle Bodywork & Painting',
    'Car Wash & Detailing', 'Towing & Roadside Assistance', 'Motorcycle Repair',
    'Bicycle Repair', 'Marine Maintenance', 'Aviation Maintenance',
  ],
  hospitality: [
    'Hotel Accommodation', 'Guesthouse Accommodation', 'Holiday Accommodation',
    'Tour Operations', 'Travel Agency Services', 'Tour Guiding', 'Ticketing Services',
    'Restaurant Services', 'Food Delivery', 'Full-Service Catering', 'Corporate Catering',
    'Wedding Catering', 'Event Catering', 'Catering Services', 'Buffet Services',
    "Cocktail & Hors d'oeuvres", 'BBQ & Grill Services', 'Dessert & Pastry Catering',
    'Beverage Services', 'Wait Staff Services', 'Wedding Planning', 'Corporate Events',
    'Birthday Parties', 'Conference Planning', 'Venue Sourcing', 'Event Decoration',
    'Venue Decoration', 'Floral Design', 'Event Staffing', 'Guest Coordination',
    'Invitations & Printing', 'Wedding Coordination', 'MC & Entertainment',
    'Sound & Lighting', 'Entertainment Services', 'Event Production',
    'Equipment Rental', 'Tableware Rental', 'Linens Rental', 'Photo Booth Rental',
    'Tent & Canopy Rental', 'Tables & Chairs Rental', 'Bridal Wear Rental', 'Suit & Tuxedo Rental',
  ],
  education: [
    'Training & Workshops', 'Tutoring', 'Vocational Training', 'Language Training',
    'Computer Training', 'Driving Lessons', 'Music Lessons', 'Art Lessons',
    'Sports Coaching', 'Personal Training', 'Fitness Classes', 'Yoga & Pilates',
    'Swimming Lessons', 'Childcare Services', 'Early Childhood Education',
    'Educational Consulting', 'Career Counselling', 'Research Services', 'Library Services',
  ],
  health: [
    'Medical Consultation', 'Nursing Services', 'Dental Services', 'Optometry',
    'Laboratory Testing', 'Diagnostic Imaging', 'Physiotherapy', 'Occupational Therapy',
    'Speech Therapy', 'Mental Health Counselling', 'Nutrition & Dietetics',
    'Home Healthcare', 'Elderly Care Services', 'Ambulance Services',
    'Veterinary Services', 'Pet Grooming', 'Pet Boarding', 'Animal Training',
  ],
  industry: [
    'Agricultural Consulting', 'Land Preparation', 'Planting Services', 'Crop Spraying',
    'Harvesting Services', 'Irrigation Installation', 'Grain Milling', 'Food Processing',
    'Livestock Breeding', 'Animal Vaccination', 'Aquaculture Services',
    'Forestry Services', 'Equipment Maintenance', 'Machining Services',
    'Contract Manufacturing', 'Packaging Services', 'Quality Inspection',
    'Calibration Services', 'Engineering Design', 'Environmental Consulting',
    'Recycling Services', 'Mining Support Services', 'Energy Consulting',
    'Utility Services', 'Water Supply Services', 'Funeral Services', 'Other Services',
  ],
};

export const ADDITIONAL_PRODUCT_GROUPS = {
  agriculture: [
    'Seeds & Seedlings', 'Fertilizers', 'Organic Fertilizers', 'Crop Protection Products',
    'Animal Feed', 'Feed Supplements', 'Livestock', 'Poultry & Chicks', 'Fish Fingerlings',
    'Veterinary Medicines', 'Animal Health Supplies', 'Irrigation Equipment',
    'Greenhouse Materials', 'Farm Machinery', 'Tractor Parts', 'Beekeeping Equipment',
    'Fishing Equipment', 'Aquaculture Equipment', 'Forestry Equipment', 'Fresh Flowers',
    'Ornamental Plants', 'Nursery Plants', 'Animal Bedding', 'Grain Storage Equipment',
  ],
  industrial: [
    'Industrial Machinery', 'Machine Tools', 'Hydraulic Equipment', 'Pneumatic Equipment',
    'Automation & Control Equipment', 'Industrial Sensors', 'Compressors',
    'Lifting & Hoisting Equipment', 'Material Handling Equipment', 'Forklifts',
    'Laboratory Equipment', 'Scientific Instruments', 'Test & Measurement Equipment',
    'Commercial Refrigeration', 'Commercial Kitchen Equipment', 'Textile Machinery',
    'Printing Machinery', 'Food Processing Equipment', 'Mining Equipment',
    'Construction Machinery', 'Agricultural Machinery', 'Industrial Gases',
    'Metal Ores', 'Steel Products', 'Aluminium Products', 'Copper Products',
    'Timber & Lumber', 'Paper & Pulp', 'Glass Materials', 'Ceramics',
    'Composite Materials', 'Recycled Materials', 'Pest Control Products',
  ],
  energy: [
    'Petrol', 'Diesel', 'Kerosene', 'LPG & Cooking Gas', 'Biofuels', 'Coal',
    'Solar Panels', 'Solar Inverters', 'Charge Controllers', 'Energy Storage Batteries',
    'Wind Power Equipment', 'Power Distribution Equipment', 'Electric Vehicle Chargers',
    'Heating Equipment', 'Ventilation Equipment', 'Air Conditioning Equipment',
  ],
  transport: [
    'Cars & Light Vehicles', 'Commercial Vehicles', 'Motorcycles', 'Bicycles',
    'Vehicle Spare Parts', 'Tyres & Tubes', 'Vehicle Batteries', 'Engine Parts',
    'Braking Systems', 'Transmission Parts', 'Suspension & Steering Parts',
    'Vehicle Body Parts', 'Vehicle Lighting', 'Vehicle Accessories',
    'Trailers & Trailer Parts', 'Boats & Marine Equipment', 'Aircraft Parts',
    'Navigation Equipment', 'Vehicle Care Products',
  ],
  electronics: [
    'Computers & Laptops', 'Computer Components', 'Computer Peripherals',
    'Mobile Phones', 'Tablets', 'Televisions', 'Audio Equipment', 'Cameras & Lenses',
    'Networking Equipment', 'Servers & Storage', 'Printers & Scanners',
    'POS Equipment', 'Barcode Scanners', 'Receipt Printers', 'Ink & Toner',
    'Projectors', 'Video Games & Consoles', 'Wearable Technology', 'Smart Home Devices',
    'Electronic Components', 'Drones & Accessories', 'Software Licenses',
    'Digital Downloads', 'E-books', 'Digital Templates', 'Telecommunication Equipment',
  ],
  home: [
    'Living Room Furniture', 'Bedroom Furniture', 'Office Furniture',
    'Outdoor Furniture', 'Mattresses', 'Curtains & Blinds', 'Carpets & Rugs',
    'Home Decor', 'Wall Art & Frames', 'Bathroom Accessories', 'Storage & Shelving',
    'Commercial Furniture', 'Furniture Fittings', 'Home Appliances',
    'Refrigerators & Freezers', 'Cookers & Ovens', 'Washing Machines',
    'Water Purifiers', 'Vacuum Cleaners', 'Sewing Machines',
  ],
  fashion: [
    "Men's Clothing", "Women's Clothing", "Children's Clothing", 'Baby Clothing',
    'Sportswear', 'Workwear & Uniforms', 'Protective Clothing', 'Traditional Clothing',
    'Bridal Wear', 'Formal Wear', 'Jewellery', 'Fashion Accessories', 'Luggage',
    'Textile Fabrics', 'Yarn & Thread', 'Leather & Leather Goods',
    'Buttons & Zippers', 'Embroidery Supplies', 'Costumes',
  ],
  health: [
    'Hospital Equipment', 'Dental Equipment', 'Dental Supplies', 'Diagnostic Equipment',
    'Rehabilitation Equipment', 'Assistive Devices', 'Hearing Aids', 'Eyeglass Frames',
    'Contact Lenses', 'Prosthetics & Orthotics', 'Sterilization Equipment',
    'Laboratory Reagents', 'Surgical Instruments', 'Hospital Furniture',
  ],
  leisure: [
    'Sports Equipment', 'Fitness Equipment', 'Camping & Hiking Equipment',
    'Outdoor Recreation Equipment', 'Musical Instruments', 'Music Accessories',
    'Art & Craft Supplies', 'Collectibles', 'Antiques', 'Board Games & Puzzles',
    'Educational Toys', 'Learning Materials', 'Religious Books', 'Awards & Trophies',
    'Playground Equipment', 'Swimming Pool Supplies', 'Pet Accessories',
    'Aquariums & Accessories', 'Pet Housing', 'Packaging & Shipping Supplies',
  ],
};

export const categoryNameKey = name => String(name || '').normalize('NFKC').trim().replace(/\s+/g, ' ').toLowerCase();
export const categorySlug = name => categoryNameKey(name).replace(/[^\p{L}\p{N}]+/gu, '-').replace(/^-|-$/g, '');
