// Only truly universal categories that apply to every business type
const COMMON_PRODUCT_CATEGORIES = [
  { name: 'Other', slug: 'other' },
];

const BUSINESS_TYPE_CATEGORY_MAP = {
  retail: [
    'General Merchandise',
    'Household Items',
    'Household Plastics',
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Spices & Condiments',
    'Cereals & Grains',
    'Canned Goods',
    'Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Energy Drinks',
    'Tea & Coffee',
    'Alcoholic Beverages',
    'Wines & Spirits',
    'Beer',
    'Tobacco Products',
    'Vapes & E-Cigarettes',
    'Dairy Products',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Ice Cream',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Seafood',
    'Frozen Foods',
    'Ready Meals',
    'Pasta & Noodles',
    'Rice & Grains',
    'Beans & Legumes',
    'Nuts & Dried Fruits',
    'Spreads & Jams',
    'Honey',
    'Sauces & Dressings',
    'Salt & Sugar',
    'Flour & Baking',
    'Breakfast Foods',
    'Health & Wellness',
    'Personal Care',
    'Hair Care',
    'Cosmetics',
    'Beauty Products',
    'Makeup',
    'Skin Care',
    'Moisturizers',
    'Lip Care',
    'Nail Care',
    'Shaving Supplies',
    'Perfumes & Deodorants',
    'Soaps & Body Wash',
    'Laundry & Fabric Care',
    'Detergents',
    'Baby Products',
    'Diapers & Wipes',
    'Baby Food',
    'Cleaning Supplies',
    'Pest Control',
    'Air Fresheners',
    'Oral Care',
    'Feminine Care',
    'Sanitary Pads',
    'Condoms',
    'Paper Products',
    'Disposable Products',
    'Stationery & Office Supplies',
    'School Supplies',
    'Books & Magazines',
    'Greeting Cards',
    'Gift Wrapping',
    'Footwear & Clothing',
    'Underwear & Socks',
    'Bedding & Linens',
    'Toys & Gifts',
    'Batteries & Electrical',
    'Hardware & Security',
    'Shoe Care',
    'Kitchenware',
    'Cookware',
    'Utensils & Cutlery',
    'Glassware',
    'Plastic Containers',
    'Food Storage',
    'Candles & Religious Items',
    'Incense & Air Fresheners',
    'Pet Supplies',
    'Pet Food',
    'Phone Accessories',
    'First Aid',
    'Matches & Lighters',
    'Charcoal & Firewood',
    'Solar Products',
    'Gas & Accessories',
    'Umbrellas',
    'Water Bottles',
    'Lunch Boxes',
    'Cooler Boxes',
    'Water Storage',
    'Sewing & Knitting',
    'Locks & Padlocks',
    'Insect Repellent',
    'Vitamins & Supplements',
    'Eggs',
    'Soups & Stocks',
    'Pickles & Relishes',
    'Baking Ingredients',
    'Snack Bars & Cereal Bars',
    'Lighting & Bulbs',
    'Small Appliances',
    'Wraps & Flatbreads',
    'Baby Formula & Infant Milk',
    'Chewing Gum & Mints',
    'Instant Foods',
    'Cooking Fat & Shortening',
    'Herbs & Seasonings',
    'Crockery',
    'Cleaning Equipment',
    'Plant-Based & Vegan Foods',
    'Frozen Desserts',
    'Pet Treats',
    'Crisps & Snack Foods',
    'Biscuits & Cookies',
    'Breakfast Cereal',
    'Butter & Margarine',
    'Yogurt & Cream',
    'Party Supplies',
    'Cooking Wine & Vinegar',
    'Coconut Products',
    'Ice & Ice Bags',
    'Chocolate & Sweets',
    'Deli Meats & Sausages',
    'Fresh Herbs',
    'Frozen Vegetables',
    'Frozen Fruits',
    'Canned Fish & Meat',
    'Powdered & UHT Milk',
    'Condensed & Evaporated Milk',
    'Religious & Cultural Items',
    'Sports & Outdoors',
    'Dietary & Special Needs',
    'Gluten-Free Foods',
    'Sugar-Free Foods',
    'Local & Imported Foods',
    'Electronics & Accessories',
    'Watches & Accessories',
    'Bags & Wallets',
    'Sunglasses & Eyewear',
  ],
  supermarket: [
    'General Merchandise',
    'Household Items',
    'Household Plastics',
    'Wholesale Goods',
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Spices & Condiments',
    'Cereals & Grains',
    'Canned Goods',
    'Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Energy Drinks',
    'Tea & Coffee',
    'Alcoholic Beverages',
    'Wines & Spirits',
    'Beer',
    'Tobacco Products',
    'Dairy Products',
    'Cheese',
    'Butchery',
    'Deli & Cold Cuts',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Ice Cream',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Seafood',
    'Frozen Foods',
    'Ready Meals',
    'Pasta & Noodles',
    'Rice & Grains',
    'Beans & Legumes',
    'Nuts & Dried Fruits',
    'Spreads & Jams',
    'Honey',
    'Sauces & Dressings',
    'Salt & Sugar',
    'Flour & Baking',
    'Breakfast Foods',
    'Organic & Health Foods',
    'Baby Food',
    'Personal Care',
    'Hair Care',
    'Cosmetics',
    'Beauty Products',
    'Makeup',
    'Skin Care',
    'Moisturizers',
    'Lip Care',
    'Nail Care',
    'Shaving Supplies',
    'Perfumes & Deodorants',
    'Soaps & Body Wash',
    'Laundry & Fabric Care',
    'Detergents',
    'Baby Products',
    'Diapers & Wipes',
    'Cleaning Supplies',
    'Pest Control',
    'Air Fresheners',
    'Oral Care',
    'Feminine Care',
    'Sanitary Pads',
    'Condoms',
    'Health & Wellness',
    'Vitamins & Supplements',
    'First Aid',
    'Insect Repellent',
    'Paper Products',
    'Disposable Products',
    'Stationery & Office Supplies',
    'School Supplies',
    'Books & Magazines',
    'Footwear & Clothing',
    'Underwear & Socks',
    'Bedding & Linens',
    'Batteries & Electrical',
    'Kitchenware',
    'Cookware',
    'Utensils & Cutlery',
    'Glassware',
    'Plastic Containers',
    'Food Storage',
    'Pet Supplies',
    'Pet Food',
    'Garden Supplies',
    'Toys & Gifts',
    'Phone Accessories',
    'Tobacco Products',
    'Vapes & E-Cigarettes',
    'Matches & Lighters',
    'Charcoal & Firewood',
    'Solar Products',
    'Gas & Accessories',
    'Umbrellas',
    'Eggs',
    'Cheese',
    'Butchery',
    'Deli & Cold Cuts',
    'Organic & Health Foods',
    'Spreads & Jams',
    'Honey',
    'Breakfast Foods',
    'Energy Drinks',
    'Nuts & Dried Fruits',
    'Soups & Stocks',
    'Pickles & Relishes',
    'Baking Ingredients',
    'Snack Bars & Cereal Bars',
    'Lighting & Bulbs',
    'Small Appliances',
    'Wraps & Flatbreads',
    'Baby Formula & Infant Milk',
    'Chewing Gum & Mints',
    'Instant Foods',
    'Cooking Fat & Shortening',
    'Herbs & Seasonings',
    'Crockery',
    'Cleaning Equipment',
    'Plant-Based & Vegan Foods',
    'Frozen Desserts',
    'Pet Treats',
    'Crisps & Snack Foods',
    'Biscuits & Cookies',
    'Breakfast Cereal',
    'Butter & Margarine',
    'Yogurt & Cream',
    'Party Supplies',
    'Cooking Wine & Vinegar',
    'Coconut Products',
    'Ice & Ice Bags',
    'Chocolate & Sweets',
    'Deli Meats & Sausages',
    'Fresh Herbs',
    'Frozen Vegetables',
    'Frozen Fruits',
    'Canned Fish & Meat',
    'Powdered & UHT Milk',
    'Condensed & Evaporated Milk',
    'Religious & Cultural Items',
    'Sports & Outdoors',
    'Dietary & Special Needs',
    'Gluten-Free Foods',
    'Sugar-Free Foods',
    'Local & Imported Foods',
    'Electronics & Accessories',
    'Watches & Accessories',
    'Bags & Wallets',
    'Sunglasses & Eyewear',
    'Vapes & E-Cigarettes',
    'Condoms',
    'Health & Wellness',
    'Vitamins & Supplements',
    'First Aid',
    'Insect Repellent',
    'Hardware & Security',
    'Shoe Care',
    'Sewing & Knitting',
    'Locks & Padlocks',
    'Water Bottles',
    'Lunch Boxes',
    'Cooler Boxes',
    'Water Storage',
    'Greeting Cards',
    'Gift Wrapping',
    'Underwear & Socks',
    'Toys & Gifts',
    'Candles & Religious Items',
    'Incense & Air Fresheners',
  ],
  wholesale: [
    'General Merchandise',
    'Household Items',
    'Household Plastics',
    'Wholesale Goods',
    'Bulk Foods',
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Spices & Condiments',
    'Cereals & Grains',
    'Canned Goods',
    'Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Tea & Coffee',
    'Alcoholic Beverages',
    'Tobacco Products',
    'Dairy Products',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Frozen Foods',
    'Rice & Grains',
    'Beans & Legumes',
    'Flour & Baking',
    'Salt & Sugar',
    'Sauces & Dressings',
    'Personal Care',
    'Hair Care',
    'Cosmetics',
    'Beauty Products',
    'Skin Care',
    'Perfumes & Deodorants',
    'Soaps & Body Wash',
    'Oral Care',
    'Laundry & Fabric Care',
    'Detergents',
    'Baby Products',
    'Diapers & Wipes',
    'Feminine Care',
    'Sanitary Pads',
    'Cleaning Supplies',
    'Pest Control',
    'Air Fresheners',
    'Paper Products',
    'Disposable Products',
    'Bulk Packaging',
    'Stationery & Office Supplies',
    'School Supplies',
    'Footwear & Clothing',
    'Bedding & Linens',
    'Hardware & Security',
    'Batteries & Electrical',
    'Kitchenware',
    'Cookware',
    'Utensils & Cutlery',
    'Glassware',
    'Plastic Containers',
    'Food Storage',
    'Agricultural Supplies',
    'Farm Inputs',
    'Industrial Cleaning',
    'Pet Supplies',
    'Pet Food',
    'First Aid',
    'Vitamins & Supplements',
    'Insect Repellent',
    'Matches & Lighters',
    'Charcoal & Firewood',
    'Solar Products',
    'Gas & Accessories',
    'Confectionery',
    'Nuts & Dried Fruits',
    'Spreads & Jams',
    'Honey',
    'Breakfast Foods',
    'Energy Drinks',
    'Eggs',
    'Soups & Stocks',
    'Pickles & Relishes',
    'Baking Ingredients',
    'Snack Bars & Cereal Bars',
    'Lighting & Bulbs',
    'Small Appliances',
    'Wraps & Flatbreads',
    'Baby Formula & Infant Milk',
    'Chewing Gum & Mints',
    'Instant Foods',
    'Cooking Fat & Shortening',
    'Herbs & Seasonings',
    'Crockery',
    'Cleaning Equipment',
    'Plant-Based & Vegan Foods',
    'Frozen Desserts',
    'Pet Treats',
    'Crisps & Snack Foods',
    'Biscuits & Cookies',
    'Breakfast Cereal',
    'Butter & Margarine',
    'Yogurt & Cream',
    'Party Supplies',
    'Cooking Wine & Vinegar',
    'Coconut Products',
    'Ice & Ice Bags',
    'Chocolate & Sweets',
    'Deli Meats & Sausages',
    'Fresh Herbs',
    'Frozen Vegetables',
    'Frozen Fruits',
    'Canned Fish & Meat',
    'Powdered & UHT Milk',
    'Condensed & Evaporated Milk',
    'Religious & Cultural Items',
    'Sports & Outdoors',
    'Dietary & Special Needs',
    'Gluten-Free Foods',
    'Sugar-Free Foods',
    'Local & Imported Foods',
    'Electronics & Accessories',
    'Watches & Accessories',
    'Bags & Wallets',
    'Sunglasses & Eyewear',
    'Cheese',
    'Butchery',
    'Deli & Cold Cuts',
    'Organic & Health Foods',
    'Vapes & E-Cigarettes',
    'Condoms',
    'Health & Wellness',
    'Oral Care',
    'Feminine Care',
    'Sanitary Pads',
    'Books & Magazines',
    'Underwear & Socks',
    'Toys & Gifts',
    'Garden Supplies',
    'Shoe Care',
    'Sewing & Knitting',
    'Locks & Padlocks',
    'Water Bottles',
    'Lunch Boxes',
    'Cooler Boxes',
    'Water Storage',
    'Candles & Religious Items',
    'Incense & Air Fresheners',
    'Umbrellas',
  ],
  pharmacy: [
    'Health & Wellness',
    'Personal Care',
    'Hair Care',
    'Perfumes & Deodorants',
    'Soaps & Body Wash',
    'Oral Care',
    'Feminine Care',
    'Sanitary Pads',
    'Condoms',
    'Pregnancy Tests',
    'Baby Products',
    'Diapers & Wipes',
    'Baby Food',
    'Baby Bath & Skin',
    'Medical Supplies',
    'Pharmaceuticals',
    'Prescription Medicines',
    'Over-the-Counter Medicines',
    'Cold & Flu Remedies',
    'Pain Relief',
    'Antacids & Digestive',
    'Cough Syrups',
    'Antiseptics',
    'Beauty Products',
    'Cosmetics',
    'First Aid',
    'First Aid Kits',
    'Vitamins & Supplements',
    'Skin Care',
    'Sunscreen',
    'Medical Devices',
    'Thermometers',
    'Blood Pressure Monitors',
    'Glucometers & Test Strips',
    'Surgical Masks',
    'Hand Sanitizer',
    'Gloves',
    'Syringes & Needles',
    'Cotton Wool & Swabs',
    'Bandages & Dressings',
    'Incontinence Products',
    'Compression Wear',
    'Orthopedic Supports',
    'Mobility Aids',
    'Reading Glasses',
    'Contact Lens Solutions',
    'Eye Care',
    'Ear Care',
    'Foot Care',
    'Shaving Supplies',
    'Insect Repellent',
    'Maternity Care',
    'Elderly Care',
  ],
  hardware: [
    'Electrical Supplies',
    'Electric Cables & Wires',
    'Switches & Sockets',
    'Circuit Breakers',
    'Lighting & Bulbs',
    'LED Lights',
    'Hardware Tools',
    'Hand Tools',
    'Power Tools',
    'Measuring Tools',
    'Cutting Tools',
    'Nails & Screws',
    'Fasteners',
    'Hinges & Fittings',
    'Door Hardware',
    'Window Hardware',
    'Plumbing Accessories',
    'Pipes & Fittings',
    'Valves & Taps',
    'Pumps',
    'Building Hardware',
    'Hardware & Security',
    'Security Cameras',
    'Alarm Systems',
    'Locks & Padlocks',
    'Safes',
    'Batteries & Electrical',
    'Extension Cords',
    'Power Strips',
    'Building Materials',
    'Cement & Concrete',
    'Sand & Aggregate',
    'Bricks & Blocks',
    'Tiles',
    'Roofing Materials',
    'Roofing Sheets',
    'Ceiling Materials',
    'Floor Materials',
    'Wall Materials',
    'Insulation',
    'Paints',
    'Paint Supplies',
    'Plumbing',
    'Electrical',
    'Hardware',
    'Welding Supplies',
    'Welding Wire',
    'Adhesives & Sealants',
    'Abrasives',
    'Lubricants & Oils',
    'Safety Equipment',
    'Garden Tools',
    'Water Tanks',
    'Solar Products',
    'Generators',
    'Ladders & Scaffolding',
    'Wheelbarrows',
    'Fencing',
    'Wire Mesh',
    'Chains & Ropes',
    'Tarps & Covers',
    'Door Bells',
  ],
  restaurant: [
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Cooking Fat',
    'Spices & Condiments',
    'Herbs & Seasonings',
    'Sauces & Dressings',
    'Rice & Grains',
    'Pasta & Noodles',
    'Beans & Legumes',
    'Flour & Baking',
    'Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Tea & Coffee',
    'Dairy Products',
    'Cheese',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Seafood',
    'Frozen Foods',
    'Kitchenware',
    'Cookware',
    'Utensils & Cutlery',
    'Glassware',
    'Crockery',
    'Disposable Products',
    'Takeaway Containers',
    'Paper Products',
    'Napkins & Tissues',
    'Cleaning Supplies',
    'Pest Control',
    'Charcoal & Firewood',
    'Packaging Materials',
    'Uniforms & Aprons',
    'Bar Supplies',
  ],
  bar: [
    'Beverages',
    'Alcoholic Beverages',
    'Wines & Spirits',
    'Beer',
    'Cocktail Mixers',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Energy Drinks',
    'Food & Grocery',
    'Cooking Oil',
    'Snacks',
    'Confectionery',
    'Bar Snacks',
    'Garnishes',
    'Ice & Ice Bags',
    'Glassware',
    'Bar Supplies',
    'Bottle Openers',
    'Coasters',
    'Disposable Products',
    'Paper Products',
    'Napkins & Tissues',
    'Cleaning Supplies',
  ],
  restaurant_bar: [
    'Beverages',
    'Alcoholic Beverages',
    'Wines & Spirits',
    'Beer',
    'Cocktail Mixers',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Tea & Coffee',
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Cooking Fat',
    'Spices & Condiments',
    'Herbs & Seasonings',
    'Sauces & Dressings',
    'Rice & Grains',
    'Pasta & Noodles',
    'Flour & Baking',
    'Dairy Products',
    'Cheese',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Seafood',
    'Frozen Foods',
    'Kitchenware',
    'Cookware',
    'Utensils & Cutlery',
    'Glassware',
    'Crockery',
    'Bar Supplies',
    'Ice & Ice Bags',
    'Disposable Products',
    'Takeaway Containers',
    'Paper Products',
    'Napkins & Tissues',
    'Cleaning Supplies',
    'Pest Control',
    'Charcoal & Firewood',
    'Packaging Materials',
    'Uniforms & Aprons',
  ],
  cafe: [
    'Beverages',
    'Tea & Coffee',
    'Coffee Beans',
    'Tea Bags',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Syrups & Flavorings',
    'Milk Alternatives',
    'Sugar & Sweeteners',
    'Bakery',
    'Cake & Pastries',
    'Cookies & Biscuits',
    'Snacks',
    'Confectionery',
    'Sandwiches',
    'Salads',
    'Wraps',
    'Food & Grocery',
    'Dairy Products',
    'Kitchenware',
    'Glassware',
    'Crockery',
    'Disposable Products',
    'Takeaway Containers',
    'Paper Products',
    'Napkins & Tissues',
    'Cleaning Supplies',
  ],
  coffee_shop: [
    'Beverages',
    'Tea & Coffee',
    'Coffee Beans',
    'Tea Bags',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Syrups & Flavorings',
    'Milk Alternatives',
    'Sugar & Sweeteners',
    'Bakery',
    'Cake & Pastries',
    'Cookies & Biscuits',
    'Snacks',
    'Confectionery',
    'Sandwiches',
    'Food & Grocery',
    'Dairy Products',
    'Kitchenware',
    'Glassware',
    'Crockery',
    'Disposable Products',
    'Takeaway Containers',
    'Paper Products',
    'Napkins & Tissues',
    'Cleaning Supplies',
  ],
  fast_food: [
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Cooking Fat',
    'Spices & Condiments',
    'Sauces & Dressings',
    'Burger Buns & Rolls',
    'Pizza Ingredients',
    'Fries & Potatoes',
    'Rice & Grains',
    'Pasta & Noodles',
    'Flour & Baking',
    'Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Dairy Products',
    'Meat & Poultry',
    'Frozen Foods',
    'Snacks',
    'Confectionery',
    'Disposable Products',
    'Takeaway Containers',
    'Paper Products',
    'Napkins & Tissues',
    'Cleaning Supplies',
    'Packaging Materials',
    'Charcoal & Firewood',
  ],
  hotel_restaurant: [
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Cooking Fat',
    'Spices & Condiments',
    'Herbs & Seasonings',
    'Sauces & Dressings',
    'Rice & Grains',
    'Pasta & Noodles',
    'Flour & Baking',
    'Beverages',
    'Alcoholic Beverages',
    'Wines & Spirits',
    'Beer',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Tea & Coffee',
    'Dairy Products',
    'Cheese',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Seafood',
    'Frozen Foods',
    'Kitchenware',
    'Cookware',
    'Utensils & Cutlery',
    'Glassware',
    'Crockery',
    'Bar Supplies',
    'Disposable Products',
    'Takeaway Containers',
    'Paper Products',
    'Napkins & Tissues',
    'Cleaning Supplies',
    'Cleaning Equipment',
    'Pest Control',
    'Toiletries',
    'Bedding & Linens',
    'Towels',
    'Guest Supplies',
    'Laundry Supplies',
    'Uniforms & Aprons',
    'Charcoal & Firewood',
  ],
  bakery: [
    'Bakery',
    'Flour & Baking',
    'Yeast & Leavening',
    'Icing & Decorations',
    'Cake Mixes',
    'Baking Trays',
    'Mixing Bowls',
    'Measuring Tools',
    'Oven Supplies',
    'Beverages',
    'Tea & Coffee',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Dairy Products',
    'Eggs',
    'Snacks',
    'Confectionery',
    'Food & Grocery',
    'Cooking Oil',
    'Spices & Condiments',
    'Fruits',
    'Kitchenware',
    'Glassware',
    'Paper Products',
    'Disposable Products',
    'Bread Bags',
    'Cake Boxes',
    'Packaging Materials',
    'Cleaning Supplies',
  ],
  service: [
    'General Services',
    'Consultation',
    'Tools & Equipment',
    'Consumables',
    'Uniforms',
    'Safety Gear',
    'Spare Parts',
    'Office Supplies',
  ],
  salon_spa: [
    'Personal Care',
    'Hair Care',
    'Shampoos & Conditioners',
    'Hair Color & Dye',
    'Hair Treatments',
    'Styling Products',
    'Hair Accessories',
    'Wigs & Extensions',
    'Barber Supplies',
    'Perfumes & Deodorants',
    'Soaps & Body Wash',
    'Health & Wellness',
    'Beauty Products',
    'Cosmetics',
    'Makeup',
    'Makeup Brushes',
    'Makeup Removers',
    'Skin Care',
    'Moisturizers',
    'Sunscreen',
    'Lip Care',
    'Nail Care',
    'Manicure Tools',
    'Pedicure Tools',
    'Waxing Supplies',
    'Threading Supplies',
    'Spa Products',
    'Massage Oils',
    'Aromatherapy',
    'Salon Equipment',
    'Salon Furniture',
    'Towels & Robes',
    'Facial Treatments',
    'Body Treatments',
    'Scrubs & Exfoliants',
    'Disposable Products',
    'Paper Products',
    'Cleaning Supplies',
  ],
  bridal_groom: [
    'Bridal Makeup',
    'Groom Grooming',
    'Bridal Hairstyling',
    'Groom Hairstyling',
    'Bridal Attire & Accessories',
    'Groom Attire & Accessories',
    'Bridal Mehndi/Henna',
    'Pre-Wedding Skincare',
    'Bridal Jewelry',
    'Groom Accessories',
    'Wedding Photography',
    'Videography Services',
    'Wedding Planning',
    'Venue Decoration',
    'Floral Arrangements',
    'Bridal Bouquets',
    'Wedding Cakes',
    'Catering Services',
    'Wedding Invitations',
    'Transport & Logistics',
    'Bridal Wear Rental',
    'Suit & Tuxedo Rental',
    'Bridal Trial Sessions',
    'Pre-Wedding Spa',
    'Post-Wedding Spa',
    'Wedding Coordination',
    'MC & Entertainment',
    'Sound & Lighting',
    'Event Staffing',
  ],
  barber_shop: [
    'Haircuts & Styling',
    'Beard Trimming & Shaping',
    'Razor Shaves',
    'Hair Coloring',
    'Scalp Treatment',
    'Hair Wash & Conditioning',
    'Kids Haircuts',
    'Hot Towel Service',
    'Facial Grooming',
    'Ear Piercing',
    'Barber Supplies',
    'Clippers & Trimmers',
    'Razors & Blades',
    'Shaving Cream & Gel',
    'Aftershave & Toners',
    'Hair Products',
    'Styling Gel & Wax',
    'Barber Chairs',
    'Mirrors & Stations',
    'Sanitization Supplies',
    'Capes & Aprons',
    'Towels & Neck Strips',
  ],
  consulting: [
    'Business Consulting',
    'Strategy Planning',
    'Financial Advisory',
    'Tax Consulting',
    'Legal Services',
    'HR Consulting',
    'Marketing Consulting',
    'IT Consulting',
    'Digital Transformation',
    'Process Optimization',
    'Risk Assessment',
    'Compliance Advisory',
    'Project Management',
    'Change Management',
    'Market Research',
    'Feasibility Studies',
    'Business Registration',
    'License & Permits',
    'Audit Services',
    'Training & Workshops',
  ],
  it_services: [
    'Software Development',
    'Web Development',
    'Mobile App Development',
    'UI/UX Design',
    'Cloud Services',
    'Server Maintenance',
    'Network Installation',
    'Cybersecurity',
    'Data Recovery',
    'IT Support',
    'Hardware Repair',
    'Computer Repair',
    'Laptop Repair',
    'Phone Repair',
    'Printer Repair',
    'CCTV Installation',
    'Access Control Systems',
    'Internet Setup',
    'WiFi Installation',
    'Data Backup',
    'System Integration',
    'Database Management',
    'DevOps Services',
    'QA Testing',
  ],
  cleaning_services: [
    'Residential Cleaning',
    'Commercial Cleaning',
    'Deep Cleaning',
    'Carpet Cleaning',
    'Window Cleaning',
    'Post-Construction Cleaning',
    'Move-in/Move-out Cleaning',
    'Upholstery Cleaning',
    'Floor Polishing',
    'Pressure Washing',
    'Garden Maintenance',
    'Pest Control',
    'Waste Management',
    'Sanitization Services',
    'Disinfection Services',
    'Cleaning Supplies',
    'Cleaning Equipment',
    'Cleaning Chemicals',
  ],
  catering_services: [
    'Full-Service Catering',
    'Corporate Catering',
    'Wedding Catering',
    'Event Catering',
    'Buffet Services',
    'Cocktail & Hors d\'oeuvres',
    'BBQ & Grill Services',
    'Dessert & Pastry Catering',
    'Beverage Services',
    'Wait Staff Services',
    'Equipment Rental',
    'Tableware Rental',
    'Linens Rental',
    'Food Supplies',
    'Beverage Supplies',
    'Packaging Materials',
  ],
  photography: [
    'Wedding Photography',
    'Event Photography',
    'Portrait Photography',
    'Product Photography',
    'Corporate Photography',
    'Drone Photography',
    'Videography',
    'Video Editing',
    'Photo Editing',
    'Album Design',
    'Print Services',
    'Canvas Prints',
    'Framing Services',
    'Photo Booth Rental',
    'Lighting Equipment',
    'Camera Equipment',
    'Backdrops & Props',
  ],
  event_planning: [
    'Wedding Planning',
    'Corporate Events',
    'Birthday Parties',
    'Conference Planning',
    'Venue Sourcing',
    'Event Decoration',
    'Floral Design',
    'Sound & AV Equipment',
    'Stage & Lighting',
    'Tent & Canopy Rental',
    'Tables & Chairs Rental',
    'Event Staffing',
    'Security Services',
    'Guest Coordination',
    'Transportation',
    'Invitations & Printing',
    'Party Supplies',
  ],
  repair_shop: [
    'Hardware Tools',
    'Screwdrivers',
    'Pliers',
    'Wrenches',
    'Soldering Iron',
    'Multimeters',
    'Heat Guns',
    'Tweezers',
    'Spudgers & Pry Tools',
    'Nails & Screws',
    'Plumbing Accessories',
    'Building Hardware',
    'Hardware & Security',
    'Batteries & Electrical',
    'Electrical Supplies',
    'Spare Parts',
    'Replacement Screens',
    'Replacement Batteries',
    'Charging Ports',
    'Speakers',
    'Cameras',
    'Flex Cables',
    'Housings',
    'Mobile Accessories',
    'Phone Chargers',
    'Screen Protectors',
    'Tempered Glass',
    'Phone Cases',
    'Laptop Accessories',
    'Repair Tools',
    'Cleaning Solutions',
    'Adhesives',
  ],
  manufacturing: [
    'Industrial Supplies',
    'Spare Parts',
    'Hardware Tools',
    'Hand Tools',
    'Power Tools',
    'Building Materials',
    'Plumbing Accessories',
    'Electrical Supplies',
    'Hardware & Security',
    'Batteries & Electrical',
    'Raw Materials',
    'Chemicals',
    'Solvents',
    'Resins',
    'Plastics',
    'Metals',
    'Rubber',
    'Textiles',
    'Packaging Materials',
    'Packaging Films',
    'Labels & Stickers',
    'Safety Equipment',
    'Welding Supplies',
    'Welding Wire',
    'Adhesives & Sealants',
    'Lubricants & Oils',
    'Fasteners',
    'Machinery Parts',
    'Bearings',
    'Motors',
    'Pumps',
    'Valves',
    'Filters',
    'Conveyor Belts',
  ],
  other: [
    'General Merchandise',
    'Household Items',
    'Food & Grocery',
    'Beverages',
    'Personal Care',
    'Cleaning Supplies',
    'Stationery & Office Supplies',
    'Miscellaneous',
    'General Supplies',
  ],
};

const slugify = (value = '') => String(value)
  .trim()
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/(^-|-$)/g, '');

const normalizeBusinessType = (businessType = 'other') => {
  const value = String(businessType || 'other').trim().toLowerCase();
  if (BUSINESS_TYPE_CATEGORY_MAP[value]) return value;
  const aliases = {
    retail_store: 'retail',
    shop: 'retail',
    supermarket: 'supermarket',
    wholesale_shop: 'wholesale',
    pharmacy_store: 'pharmacy',
    hardware_store: 'hardware',
    restaurant_bar: 'restaurant_bar',
    cafe_shop: 'cafe',
    coffee: 'coffee_shop',
    fastfood: 'fast_food',
    salon: 'salon_spa',
    spa: 'salon_spa',
    bridal: 'bridal_groom',
    groom: 'bridal_groom',
    wedding: 'bridal_groom',
    barber: 'barber_shop',
    barbershop: 'barber_shop',
    consulting_firm: 'consulting',
    consultancy: 'consulting',
    it_company: 'it_services',
    tech_services: 'it_services',
    cleaning_company: 'cleaning_services',
    catering: 'catering_services',
    photographer: 'photography',
    photography_studio: 'photography',
    event_planner: 'event_planning',
    events: 'event_planning',
    repair: 'repair_shop',
    manufacturing_company: 'manufacturing',
    service_business: 'service',
  };
  return aliases[value] || 'other';
};

const buildCategoryDefinitions = (businessType = 'other') => {
  const normalizedType = normalizeBusinessType(businessType);
  const typeSpecificCategories = BUSINESS_TYPE_CATEGORY_MAP[normalizedType] || BUSINESS_TYPE_CATEGORY_MAP.other;
  const merged = [];
  const seen = new Set();
  const addCategory = (name) => {
    const slug = slugify(name);
    if (!seen.has(slug)) {
      seen.add(slug);
      merged.push({ name, slug, categoryType: 'product' });
    }
  };

  COMMON_PRODUCT_CATEGORIES.forEach((category) => addCategory(category.name));
  typeSpecificCategories.forEach((name) => addCategory(name));

  return merged;
};

export function getDefaultCategoryDefinitionsForBusinessType(businessType = 'other') {
  return buildCategoryDefinitions(businessType);
}

export function getDefaultCategorySlugsForBusinessType(businessType = 'other') {
  return new Set(getDefaultCategoryDefinitionsForBusinessType(businessType).map((category) => category.slug));
}

export function getAllDefaultCategoryDefinitions() {
  const all = [];
  const seen = new Set();
  for (const businessType of Object.keys(BUSINESS_TYPE_CATEGORY_MAP)) {
    for (const category of buildCategoryDefinitions(businessType)) {
      if (!seen.has(category.slug)) {
        seen.add(category.slug);
        all.push(category);
      }
    }
  }
  return all;
}

export function getAllDefaultCategorySlugs() {
  return new Set(getAllDefaultCategoryDefinitions().map((category) => category.slug));
}
