// Only truly universal categories that apply to every business type
const COMMON_PRODUCT_CATEGORIES = [
  { name: 'Other', slug: 'other' },
];

const BUSINESS_TYPE_CATEGORY_MAP = {
  retail: [
    'General Merchandise',
    'Household Items',
    'Household Plastics',
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Spices & Condiments',
    'Cereals & Grains',
    'Canned Goods',
    'Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Energy Drinks',
    'Tea & Coffee',
    'Alcoholic Beverages',
    'Wines & Spirits',
    'Beer',
    'Tobacco Products',
    'Vapes & E-Cigarettes',
    'Dairy Products',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Ice Cream',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Seafood',
    'Frozen Foods',
    'Ready Meals',
    'Pasta & Noodles',
    'Rice & Grains',
    'Beans & Legumes',
    'Nuts & Dried Fruits',
    'Spreads & Jams',
    'Honey',
    'Sauces & Dressings',
    'Salt & Sugar',
    'Flour & Baking',
    'Breakfast Foods',
    'Health & Wellness',
    'Personal Care',
    'Hair Care',
    'Perfumes & Deodorants',
    'Soaps & Body Wash',
    'Laundry & Fabric Care',
    'Detergents',
    'Baby Products',
    'Diapers & Wipes',
    'Baby Food',
    'Cleaning Supplies',
    'Pest Control',
    'Air Fresheners',
    'Oral Care',
    'Feminine Care',
    'Sanitary Pads',
    'Condoms',
    'Paper Products',
    'Disposable Products',
    'Stationery & Office Supplies',
    'School Supplies',
    'Books & Magazines',
    'Greeting Cards',
    'Gift Wrapping',
    'Footwear & Clothing',
    'Underwear & Socks',
    'Bedding & Linens',
    'Toys & Gifts',
    'Batteries & Electrical',
    'Hardware & Security',
    'Shoe Care',
    'Kitchenware',
    'Cookware',
    'Utensils & Cutlery',
    'Glassware',
    'Plastic Containers',
    'Food Storage',
    'Candles & Religious Items',
    'Incense & Air Fresheners',
    'Pet Supplies',
    'Phone Accessories',
    'First Aid',
    'Matches & Lighters',
    'Charcoal & Firewood',
    'Solar Products',
    'Gas & Accessories',
    'Umbrellas',
    'Water Bottles',
    'Lunch Boxes',
    'Cooler Boxes',
    'Water Storage',
    'Sewing & Knitting',
    'Locks & Padlocks',
  ],
  supermarket: [
    'General Merchandise',
    'Household Items',
    'Household Plastics',
    'Wholesale Goods',
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Spices & Condiments',
    'Cereals & Grains',
    'Canned Goods',
    'Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Energy Drinks',
    'Tea & Coffee',
    'Alcoholic Beverages',
    'Wines & Spirits',
    'Beer',
    'Tobacco Products',
    'Dairy Products',
    'Cheese',
    'Butchery',
    'Deli & Cold Cuts',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Ice Cream',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Seafood',
    'Frozen Foods',
    'Ready Meals',
    'Pasta & Noodles',
    'Rice & Grains',
    'Beans & Legumes',
    'Nuts & Dried Fruits',
    'Spreads & Jams',
    'Honey',
    'Sauces & Dressings',
    'Salt & Sugar',
    'Flour & Baking',
    'Breakfast Foods',
    'Organic & Health Foods',
    'Baby Food',
    'Personal Care',
    'Hair Care',
    'Soaps & Body Wash',
    'Laundry & Fabric Care',
    'Detergents',
    'Baby Products',
    'Diapers & Wipes',
    'Cleaning Supplies',
    'Pest Control',
    'Air Fresheners',
    'Oral Care',
    'Feminine Care',
    'Sanitary Pads',
    'Paper Products',
    'Disposable Products',
    'Stationery & Office Supplies',
    'School Supplies',
    'Books & Magazines',
    'Footwear & Clothing',
    'Bedding & Linens',
    'Batteries & Electrical',
    'Kitchenware',
    'Cookware',
    'Utensils & Cutlery',
    'Glassware',
    'Pet Supplies',
    'Pet Food',
    'First Aid',
    'Garden Supplies',
    'Toys & Gifts',
    'Phone Accessories',
  ],
  wholesale: [
    'General Merchandise',
    'Household Items',
    'Household Plastics',
    'Wholesale Goods',
    'Bulk Foods',
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Spices & Condiments',
    'Cereals & Grains',
    'Canned Goods',
    'Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Tea & Coffee',
    'Alcoholic Beverages',
    'Tobacco Products',
    'Dairy Products',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Frozen Foods',
    'Rice & Grains',
    'Beans & Legumes',
    'Flour & Baking',
    'Salt & Sugar',
    'Sauces & Dressings',
    'Personal Care',
    'Soaps & Body Wash',
    'Laundry & Fabric Care',
    'Detergents',
    'Baby Products',
    'Diapers & Wipes',
    'Feminine Care',
    'Sanitary Pads',
    'Cleaning Supplies',
    'Paper Products',
    'Disposable Products',
    'Bulk Packaging',
    'Stationery & Office Supplies',
    'School Supplies',
    'Hardware & Security',
    'Batteries & Electrical',
    'Kitchenware',
    'Cookware',
    'Glassware',
    'Agricultural Supplies',
    'Farm Inputs',
    'Industrial Cleaning',
  ],
  pharmacy: [
    'Health & Wellness',
    'Personal Care',
    'Hair Care',
    'Perfumes & Deodorants',
    'Soaps & Body Wash',
    'Oral Care',
    'Feminine Care',
    'Sanitary Pads',
    'Condoms',
    'Pregnancy Tests',
    'Baby Products',
    'Diapers & Wipes',
    'Baby Food',
    'Baby Bath & Skin',
    'Medical Supplies',
    'Pharmaceuticals',
    'Prescription Medicines',
    'Over-the-Counter Medicines',
    'Cold & Flu Remedies',
    'Pain Relief',
    'Antacids & Digestive',
    'Cough Syrups',
    'Antiseptics',
    'Beauty Products',
    'Cosmetics',
    'First Aid',
    'First Aid Kits',
    'Vitamins & Supplements',
    'Skin Care',
    'Sunscreen',
    'Medical Devices',
    'Thermometers',
    'Blood Pressure Monitors',
    'Glucometers & Test Strips',
    'Surgical Masks',
    'Hand Sanitizer',
    'Gloves',
    'Syringes & Needles',
    'Cotton Wool & Swabs',
    'Bandages & Dressings',
    'Incontinence Products',
    'Compression Wear',
    'Orthopedic Supports',
    'Mobility Aids',
    'Reading Glasses',
    'Contact Lens Solutions',
    'Eye Care',
    'Ear Care',
    'Foot Care',
    'Shaving Supplies',
    'Insect Repellent',
    'Maternity Care',
    'Elderly Care',
  ],
  hardware: [
    'Electrical Supplies',
    'Electric Cables & Wires',
    'Switches & Sockets',
    'Circuit Breakers',
    'Lighting & Bulbs',
    'LED Lights',
    'Hardware Tools',
    'Hand Tools',
    'Power Tools',
    'Measuring Tools',
    'Cutting Tools',
    'Nails & Screws',
    'Fasteners',
    'Hinges & Fittings',
    'Door Hardware',
    'Window Hardware',
    'Plumbing Accessories',
    'Pipes & Fittings',
    'Valves & Taps',
    'Pumps',
    'Building Hardware',
    'Hardware & Security',
    'Security Cameras',
    'Alarm Systems',
    'Locks & Padlocks',
    'Safes',
    'Batteries & Electrical',
    'Extension Cords',
    'Power Strips',
    'Building Materials',
    'Cement & Concrete',
    'Sand & Aggregate',
    'Bricks & Blocks',
    'Tiles',
    'Roofing Materials',
    'Roofing Sheets',
    'Ceiling Materials',
    'Floor Materials',
    'Wall Materials',
    'Insulation',
    'Paints',
    'Paint Supplies',
    'Plumbing',
    'Electrical',
    'Hardware',
    'Welding Supplies',
    'Welding Wire',
    'Adhesives & Sealants',
    'Abrasives',
    'Lubricants & Oils',
    'Safety Equipment',
    'Garden Tools',
    'Water Tanks',
    'Solar Products',
    'Generators',
    'Ladders & Scaffolding',
    'Wheelbarrows',
    'Fencing',
    'Wire Mesh',
    'Chains & Ropes',
    'Tarps & Covers',
    'Door Bells',
  ],
  restaurant: [
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Cooking Fat',
    'Spices & Condiments',
    'Herbs & Seasonings',
    'Sauces & Dressings',
    'Rice & Grains',
    'Pasta & Noodles',
    'Beans & Legumes',
    'Flour & Baking',
    'Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Tea & Coffee',
    'Dairy Products',
    'Cheese',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Seafood',
    'Frozen Foods',
    'Kitchenware',
    'Cookware',
    'Utensils & Cutlery',
    'Glassware',
    'Crockery',
    'Disposable Products',
    'Takeaway Containers',
    'Paper Products',
    'Napkins & Tissues',
    'Cleaning Supplies',
    'Pest Control',
    'Charcoal & Firewood',
    'Packaging Materials',
    'Uniforms & Aprons',
    'Bar Supplies',
  ],
  bar: [
    'Beverages',
    'Alcoholic Beverages',
    'Wines & Spirits',
    'Beer',
    'Cocktail Mixers',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Energy Drinks',
    'Food & Grocery',
    'Cooking Oil',
    'Snacks',
    'Confectionery',
    'Bar Snacks',
    'Garnishes',
    'Ice & Ice Bags',
    'Glassware',
    'Bar Supplies',
    'Bottle Openers',
    'Coasters',
    'Disposable Products',
    'Paper Products',
    'Napkins & Tissues',
    'Cleaning Supplies',
  ],
  restaurant_bar: [
    'Beverages',
    'Alcoholic Beverages',
    'Wines & Spirits',
    'Beer',
    'Cocktail Mixers',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Tea & Coffee',
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Cooking Fat',
    'Spices & Condiments',
    'Herbs & Seasonings',
    'Sauces & Dressings',
    'Rice & Grains',
    'Pasta & Noodles',
    'Flour & Baking',
    'Dairy Products',
    'Cheese',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Seafood',
    'Frozen Foods',
    'Kitchenware',
    'Cookware',
    'Utensils & Cutlery',
    'Glassware',
    'Crockery',
    'Bar Supplies',
    'Ice & Ice Bags',
    'Disposable Products',
    'Takeaway Containers',
    'Paper Products',
    'Napkins & Tissues',
    'Cleaning Supplies',
    'Pest Control',
    'Charcoal & Firewood',
    'Packaging Materials',
    'Uniforms & Aprons',
  ],
  cafe: [
    'Beverages',
    'Tea & Coffee',
    'Coffee Beans',
    'Tea Bags',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Syrups & Flavorings',
    'Milk Alternatives',
    'Sugar & Sweeteners',
    'Bakery',
    'Cake & Pastries',
    'Cookies & Biscuits',
    'Snacks',
    'Confectionery',
    'Sandwiches',
    'Salads',
    'Wraps',
    'Food & Grocery',
    'Dairy Products',
    'Kitchenware',
    'Glassware',
    'Crockery',
    'Disposable Products',
    'Takeaway Containers',
    'Paper Products',
    'Napkins & Tissues',
    'Cleaning Supplies',
  ],
  coffee_shop: [
    'Beverages',
    'Tea & Coffee',
    'Coffee Beans',
    'Tea Bags',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Syrups & Flavorings',
    'Milk Alternatives',
    'Sugar & Sweeteners',
    'Bakery',
    'Cake & Pastries',
    'Cookies & Biscuits',
    'Snacks',
    'Confectionery',
    'Sandwiches',
    'Food & Grocery',
    'Dairy Products',
    'Kitchenware',
    'Glassware',
    'Crockery',
    'Disposable Products',
    'Takeaway Containers',
    'Paper Products',
    'Napkins & Tissues',
    'Cleaning Supplies',
  ],
  fast_food: [
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Cooking Fat',
    'Spices & Condiments',
    'Sauces & Dressings',
    'Burger Buns & Rolls',
    'Pizza Ingredients',
    'Fries & Potatoes',
    'Rice & Grains',
    'Pasta & Noodles',
    'Flour & Baking',
    'Beverages',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Dairy Products',
    'Meat & Poultry',
    'Frozen Foods',
    'Snacks',
    'Confectionery',
    'Disposable Products',
    'Takeaway Containers',
    'Paper Products',
    'Napkins & Tissues',
    'Cleaning Supplies',
    'Packaging Materials',
    'Charcoal & Firewood',
  ],
  hotel_restaurant: [
    'Food & Grocery',
    'Groceries',
    'Cooking Oil',
    'Cooking Fat',
    'Spices & Condiments',
    'Herbs & Seasonings',
    'Sauces & Dressings',
    'Rice & Grains',
    'Pasta & Noodles',
    'Flour & Baking',
    'Beverages',
    'Alcoholic Beverages',
    'Wines & Spirits',
    'Beer',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Tea & Coffee',
    'Dairy Products',
    'Cheese',
    'Bakery',
    'Snacks',
    'Confectionery',
    'Fruits',
    'Vegetables',
    'Meat & Poultry',
    'Seafood',
    'Frozen Foods',
    'Kitchenware',
    'Cookware',
    'Utensils & Cutlery',
    'Glassware',
    'Crockery',
    'Bar Supplies',
    'Disposable Products',
    'Takeaway Containers',
    'Paper Products',
    'Napkins & Tissues',
    'Cleaning Supplies',
    'Cleaning Equipment',
    'Pest Control',
    'Toiletries',
    'Bedding & Linens',
    'Towels',
    'Guest Supplies',
    'Laundry Supplies',
    'Uniforms & Aprons',
    'Charcoal & Firewood',
  ],
  bakery: [
    'Bakery',
    'Flour & Baking',
    'Yeast & Leavening',
    'Icing & Decorations',
    'Cake Mixes',
    'Baking Trays',
    'Mixing Bowls',
    'Measuring Tools',
    'Oven Supplies',
    'Beverages',
    'Tea & Coffee',
    'Soft Drinks',
    'Bottled Water',
    'Juices & Cordials',
    'Dairy Products',
    'Eggs',
    'Snacks',
    'Confectionery',
    'Food & Grocery',
    'Cooking Oil',
    'Spices & Condiments',
    'Fruits',
    'Kitchenware',
    'Glassware',
    'Paper Products',
    'Disposable Products',
    'Bread Bags',
    'Cake Boxes',
    'Packaging Materials',
    'Cleaning Supplies',
  ],
  service: [
    'General Merchandise',
    'Household Items',
    'Cleaning Supplies',
    'Office Supplies',
    'Office Equipment',
    'Stationery & Office Supplies',
    'Tools & Equipment',
    'Consumables',
    'Uniforms',
    'Safety Gear',
    'Spare Parts',
  ],
  salon_spa: [
    'Personal Care',
    'Hair Care',
    'Shampoos & Conditioners',
    'Hair Color & Dye',
    'Hair Treatments',
    'Styling Products',
    'Hair Accessories',
    'Wigs & Extensions',
    'Barber Supplies',
    'Perfumes & Deodorants',
    'Soaps & Body Wash',
    'Health & Wellness',
    'Beauty Products',
    'Cosmetics',
    'Makeup',
    'Makeup Brushes',
    'Makeup Removers',
    'Skin Care',
    'Moisturizers',
    'Sunscreen',
    'Lip Care',
    'Nail Care',
    'Manicure Tools',
    'Pedicure Tools',
    'Waxing Supplies',
    'Threading Supplies',
    'Spa Products',
    'Massage Oils',
    'Aromatherapy',
    'Salon Equipment',
    'Salon Furniture',
    'Towels & Robes',
    'Facial Treatments',
    'Body Treatments',
    'Scrubs & Exfoliants',
    'Disposable Products',
    'Paper Products',
    'Cleaning Supplies',
  ],
  repair_shop: [
    'Hardware Tools',
    'Screwdrivers',
    'Pliers',
    'Wrenches',
    'Soldering Iron',
    'Multimeters',
    'Heat Guns',
    'Tweezers',
    'Spudgers & Pry Tools',
    'Nails & Screws',
    'Plumbing Accessories',
    'Building Hardware',
    'Hardware & Security',
    'Batteries & Electrical',
    'Electrical Supplies',
    'Spare Parts',
    'Replacement Screens',
    'Replacement Batteries',
    'Charging Ports',
    'Speakers',
    'Cameras',
    'Flex Cables',
    'Housings',
    'Mobile Accessories',
    'Phone Chargers',
    'Screen Protectors',
    'Tempered Glass',
    'Phone Cases',
    'Laptop Accessories',
    'Repair Tools',
    'Cleaning Solutions',
    'Adhesives',
  ],
  manufacturing: [
    'Industrial Supplies',
    'Spare Parts',
    'Hardware Tools',
    'Hand Tools',
    'Power Tools',
    'Building Materials',
    'Plumbing Accessories',
    'Electrical Supplies',
    'Hardware & Security',
    'Batteries & Electrical',
    'Raw Materials',
    'Chemicals',
    'Solvents',
    'Resins',
    'Plastics',
    'Metals',
    'Rubber',
    'Textiles',
    'Packaging Materials',
    'Packaging Films',
    'Labels & Stickers',
    'Safety Equipment',
    'Welding Supplies',
    'Welding Wire',
    'Adhesives & Sealants',
    'Lubricants & Oils',
    'Fasteners',
    'Machinery Parts',
    'Bearings',
    'Motors',
    'Pumps',
    'Valves',
    'Filters',
    'Conveyor Belts',
  ],
  other: [
    'General Merchandise',
    'Household Items',
    'Food & Grocery',
    'Beverages',
    'Personal Care',
    'Cleaning Supplies',
    'Stationery & Office Supplies',
    'Miscellaneous',
    'General Supplies',
  ],
};

const slugify = (value = '') => String(value)
  .trim()
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/(^-|-$)/g, '');

const normalizeBusinessType = (businessType = 'other') => {
  const value = String(businessType || 'other').trim().toLowerCase();
  if (BUSINESS_TYPE_CATEGORY_MAP[value]) return value;
  const aliases = {
    retail_store: 'retail',
    shop: 'retail',
    supermarket: 'supermarket',
    wholesale_shop: 'wholesale',
    pharmacy_store: 'pharmacy',
    hardware_store: 'hardware',
    restaurant_bar: 'restaurant_bar',
    cafe_shop: 'cafe',
    coffee: 'coffee_shop',
    fastfood: 'fast_food',
    salon: 'salon_spa',
    spa: 'salon_spa',
    repair: 'repair_shop',
    manufacturing_company: 'manufacturing',
    service_business: 'service',
  };
  return aliases[value] || 'other';
};

const buildCategoryDefinitions = (businessType = 'other') => {
  const normalizedType = normalizeBusinessType(businessType);
  const typeSpecificCategories = BUSINESS_TYPE_CATEGORY_MAP[normalizedType] || BUSINESS_TYPE_CATEGORY_MAP.other;
  const merged = [];
  const seen = new Set();
  const addCategory = (name) => {
    const slug = slugify(name);
    if (!seen.has(slug)) {
      seen.add(slug);
      merged.push({ name, slug, categoryType: 'product' });
    }
  };

  COMMON_PRODUCT_CATEGORIES.forEach((category) => addCategory(category.name));
  typeSpecificCategories.forEach((name) => addCategory(name));

  return merged;
};

export function getDefaultCategoryDefinitionsForBusinessType(businessType = 'other') {
  return buildCategoryDefinitions(businessType);
}

export function getDefaultCategorySlugsForBusinessType(businessType = 'other') {
  return new Set(getDefaultCategoryDefinitionsForBusinessType(businessType).map((category) => category.slug));
}

export function getAllDefaultCategoryDefinitions() {
  const all = [];
  const seen = new Set();
  for (const businessType of Object.keys(BUSINESS_TYPE_CATEGORY_MAP)) {
    for (const category of buildCategoryDefinitions(businessType)) {
      if (!seen.has(category.slug)) {
        seen.add(category.slug);
        all.push(category);
      }
    }
  }
  return all;
}

export function getAllDefaultCategorySlugs() {
  return new Set(getAllDefaultCategoryDefinitions().map((category) => category.slug));
}
