ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "attendanceLatitude" DOUBLE PRECISION;
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "attendanceLongitude" DOUBLE PRECISION;
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "attendanceRadiusMeters" INTEGER NOT NULL DEFAULT 200;